- hosts: all 
  tasks:
  - name: Install apache
    include_tasks:  apache.yml
  - name: Download Template
    include_tasks: downloadTemplate.yml 
  - name: Disable SELinux
    include_tasks: "{{ ansible_os_family }}disableSelinux.yml"